### ISSUE TITLE
National ID number not required

### ISSUE THREAD

**Issue by yavisht** [Charitable/library#10]
**library/donation-form/collect-national-id-number.php**

Is it possible to make National ID not required? When I set required to false, it does not show on the donation form.

**Comment by ericnicolaas** [comment]
Sounds like you might have your donation form set up to only show required fields. In the WP customizer, go to Charitable > Donation Form and make sure it shows all fields, not just required ones.

**Comment by yavisht** [comment]
@ericnicolaas Thanks for that, I was not aware of that option. Cheers!
