### ISSUE TITLE
Custom Field on Single campaign ID

### ISSUE THREAD

**Issue by EveVee** [Charitable/library#14]
Hi, php muppet amongst you, apologies. 

If I want to add my custom field to a single campaign ID (in this case the ID is 1722), instead of all 4 campaigns currently running, my reading on here has found that the following code should work. However, I'm getting an error returned from Code Snippets plug in telling me its incorrect. 

if ( 1722 != $form->get_campaign()->ID ) {
    return $fields;   
}

Now then, I have added it to the main code before the opening line of... 

function ed_charitable_register_item_purchased_field() {

Have I done that incorrectly, should it be inserted elsewhere? Without it the code works perfectly, but is adding the custom field to all campaigns. The error message I get is:

_The code snippet you are trying to save produced a fatal error on line 1:

Call to a member function get_campaign() on null_

Many thanks in advance for any advice.

**Comment by ericnicolaas** [comment]
@EveVee If you want to only include a field in a single campaign, you can't currently use the Donation Fields API. Instead, follow this example for the old way of adding fields:

https://github.com/Charitable/library/blob/master/donation-form/legacy/collect-national-id-number.php

It's basically a more verbose way of doing the same thing, but does allow the control over whether to show the field for certain campaigns.
