### ISSUE TITLE
Optional Custom Fields Do Not Appear, only Required Fields

### ISSUE THREAD

**Issue by tlentine** [Charitable/library#3]
Hello! I'm attempting to use the sample ed_collect_national_id_number function to add a few custom fields to a donation form. If I mark each field as required I can see them appear on the form. However, I need to only mark one of the fields as required and the rest as optional. When I do this, I am unable to see any of the optional fields. I'm VERY new to PHP, so I'm guessing this is user error, but I'd be extremely appreciative if you could take a look at my function and tell me what I'm doing wrong.
function ed_collect_student_name( $fields, Charitable_Donation_Form $form ) {
    $fields['student_name'] = array(
        'label'     => __( 'Student Name', 'your-namespace' ), 
        'type'      => 'text', 
        'priority'  => 24, 
        'value'     => $form->get_user_value( 'donor_student_name' ), 
        'required'  => true, 
        'data_type' => 'user'
    );
    $fields['student_name_2'] = array(
        'label'     => __( '2nd Student Name (optional)', 'your-namespace' ), 
        'type'      => 'text', 
        'priority'  => 25, 
        'value'     => $form->get_user_value( 'donor_student_name_2' ), 
        'required'  => false, 
        'data_type' => 'user'
    );

    return $fields;
}

**Comment by ericnicolaas** [comment]
@tlentine It sounds like your form is set up to only show required fields. Go to the Customizer and open up the Charitable > Donation Form tab. Make sure it's not set to only show required fields.

**Comment by tlentine** [comment]
@ericnicolaas That was it, thanks so much for the response. I removed the optional fields with the remove donor form fields function to achieve the desired effect. This is a great library, thanks for making it open source!

**Comment by ericnicolaas** [comment]
@tlentine Sorry, I'd missed your follow-up question. The custom fields you add to the form are saved to the database, to the donor meta record in the `wp_postmeta` table.
