### ISSUE TITLE
customizing charitable plugin

### ISSUE THREAD

**Issue by steveytaylor** [Charitable/library#4]
i've been looking through the .php files of the charitable plugin and i'm a somewhat balanced php developer but i've never tried customizing a plugin.....i'm trying to display the campaign description on the donation receipt and also i'm trying to display a certain incentive for donors which echos a simple mathematical calculation ($incentive=$donation_amount + ($donation_amount * 10)/100)). i'm not even sure where this should go. Help please, my brain's melting T_T

**Comment by ericnicolaas** [comment]
@steveytaylor Sounds like you might have figured this one out?
