### ISSUE TITLE
Possible to register a new email?

### ISSUE THREAD

**Issue by rybridge** [Charitable/library#5]
I've been looking at sending an email with offline instructions and it works with the example here. https://github.com/Charitable/library/blob/master/emails/send-donation-receipt-for-pending-offline-donations.php

But in our case we're looking to send an email before the donation receipt is sent with instructions on where to send offline donations.

Steps would be something like this:
1. User donates with and offline donation
2. Donation is set to pending and the user gets an email with direction.
3. Payment received in the mail admin marks donation as complete
4. User gets their donation receipt

I'm not sure how to approach dividing out the Donation Receipt email into two emails depending on state of the donation.

Any guidance would be appreciated.

**Comment by ericnicolaas** [comment]
@rybridge so sorry for missing this.

I'm sure you've probably worked out a solution for this, but if not this PR will basically allow you to do what you want:

https://github.com/Charitable/Charitable/pull/380
