### ISSUE TITLE
Custom Select field to campaign submission form

### ISSUE THREAD

**Issue by yavisht** [Charitable/library#6]
https://github.com/Charitable/library/blob/master/extensions/ambassadors/campaign-submission-form/add-select-field.php

Successfully added the select field but how do you retrieve data in the backend? Where do I see this data once the form is filled out?

**Comment by ericnicolaas** [comment]
@yavisht It isn't shown anywhere by default, and unfortunately it's not the easiest thing to include it somewhere. However, you could try adapting this code snippet: https://github.com/Charitable/library/blob/master/extensions/ambassadors/campaign-submission-form/add-user-details-to-funds-recipient-information.php

That will add the details to the "Funds Recipient" tab.

**Comment by yavisht** [comment]
Thank you! I registered a custom meta box and grabbed the data from post_meta.
