### ISSUE TITLE
Campaign category select box

### ISSUE THREAD

**Issue by yavisht** [Charitable/library#7]
If I have parent - child categories for campaigns, is it possible to show nested categories in the select box in the forms?
For e.g. http://jsfiddle.net/ka3ng/2/

**Comment by ericnicolaas** [comment]
@yavisht You can do that by having the options as an array of arrays. i.e.

```
$fields['campaign_category']['options'] = array(
   'Parent Category 1' => array(
      123 => 'Child Category',
      456 => 'Child Category 2',
   ),
   'Parent Category 2' => array(
      987 => 'Child Category',
      654 => 'Child Category 2',
   ),
);
```

To actually get that structure for the options, you'd need to iterate over the cats and split them based on the parent.
