### ISSUE TITLE
Add a donation programmatically

### ISSUE THREAD

**Issue by yavisht** [Charitable/library#8]
I have a custom form that needs to create an "offline" donation entry for a particular campaign on submission. Is it possible to add an offline donation entry to a particular campaign programmatically without going through the payment form?

**Comment by ericnicolaas** [comment]
@yavisht Yes, it is. The best example of how to do this is actually in our unit tests: 

https://github.com/Charitable/Charitable/blob/master/tests/helpers/charitable-donation-helper.php#L28-L48

We'll also be adding a way to add donations via the admin in Charitable 1.5.

**Comment by yavisht** [comment]
Will I have to create a Charitable_user first and then pass the user id in the array to create the donation? My form accepts name email and phone number. Is there a way to add donor data in the same array?

**Comment by ericnicolaas** [comment]
Actually, this is probably a better example https://github.com/Charitable/Charitable/blob/master/tests/unit-tests/test-donation-functions.php#L112

**Comment by ericnicolaas** [comment]
Note how it passes an array of user details -- no need to create one first.

**Comment by yavisht** [comment]
Note that I have changed **Charitable_Donation_Processor** to **Charitable_Recurring_Donation_Processor** to create a recurring donation.. 

**I have 3 questions..** @ericnicolaas 
1. Have I manipulated the 2 examples correctly to create a recurring donation?
2. Where do I see the note in the backend?
3. Why is no Donation key generated for the recurring donation? Is this normal behaviour?

```
    $donation_args = array();

    $new_donation_args = array(
        'status' => $status,
        'gateway' => 'manual',
        'note' => $_POST['employee_donation_note'],
        'campaigns' => array(
            array(
                'campaign_id' => 783,
                'amount' => $suggested_amount
            ),
        ),
        'user' => array(
            'first_name' => $_POST['employee_first_name'],
            'last_name' => $_POST['employee_last_name'],
            'email' => $_POST['employee_email'],
            'phone' => $_POST['employee_phone'],
            'employee_number' => $_POST['employee_number'],
            'allocate_donations_to' => $_POST['donation_category']
        ),
    );

    $donation_args = array_merge( $new_donation_args, $donation_args );

    if ( empty( $donation_args['campaigns'] ) || ! is_array( $donation_args['campaigns'] ) ) {
        wp_die( 'You must pass an array of campaigns to create a donation.' );
    }

    $new_donation_id = Charitable_Recurring_Donation_Processor::get_instance()->save_donation( $donation_args );

    Charitable_Recurring_Donation_Processor::destroy();

    var_dump($new_donation_id);

```

**Comment by ericnicolaas** [comment]
@yavisht You don't need to use `Charitable_Recurring_Donation_Processor`; use `Charitable_Donation_Processor` instead. The former just hooks into what is happening in the main donation processor. 

Instead, you can pass a few Recurring Donations-specific arguments to the processor: 

- donation_period - The period of the recurring donation. Currently `month` is the only argument that is fully supported in all gateways. 
- donation_interval - Combined with the period, this gives you control over how frequently the recurring donations happen. In Recurring Donations, we hardcode this to 1. i.e. Every month. Theoretically it could be set to 2 for every second month, 3 for every third month, etc. Again, that isn't fully supported yet and may not work with all the gateways.

```
 $new_donation_args = array(
        'status' => $status,
        'gateway' => 'manual',
        'note' => $_POST['employee_donation_note'],
        'donation_period' => 'month',
       'donation_interval' => 1,
        'campaigns' => array(
            array(
                'campaign_id' => 783,
                'amount' => $suggested_amount
            ),
        ),
        'user' => array(
            'first_name' => $_POST['employee_first_name'],
            'last_name' => $_POST['employee_last_name'],
            'email' => $_POST['employee_email'],
            'phone' => $_POST['employee_phone'],
            'employee_number' => $_POST['employee_number'],
            'allocate_donations_to' => $_POST['donation_category']
        ),
    );
```

`note` is stored as the `post_content` of the donation, but it's not really shown anywhere; it's effectively unused. What is the `employee_donation_note`? Is that like a comment? 

I think if you use `Charitable_Donation_Processor` it will fix the problem with the donation key not getting generated.

**Comment by yavisht** [comment]
@ericnicolaas thanks for the clarification. Yes employee_donation_note is just a basic comment that the user will add along with the donation.

**Comment by ericnicolaas** [comment]
@yavisht We actually have a Donor Comments extension coming out once we have released 1.5. Maybe that would be worth using instead? It's still in beta, and would require you to roll an Alpha version of Charitable 1.5 for now.

**Comment by yavisht** [comment]
@ericnicolaas that's great news. We have removed the note functionality for now. Once the Donor Comments is out, will the above code the ability to add the donor comment through Charitable_Donation_Processor?

**Comment by ericnicolaas** [comment]
No, it won't. Instead, you should be able to pass the comment along as `donor_comment` in the values to the processor. But I haven't tested that. Might be worth trying it out to make sure it works the way you'd want?

**Comment by yavisht** [comment]
Open to trying it out.. Will do when its released.

**Comment by ericnicolaas** [comment]
No worries.
