### ISSUE TITLE
Add National ID number to more than 1 campaign

### ISSUE THREAD

**Issue by yavisht** [Charitable/library#9]
**library/donation-form/collect-national-id-number.php**

What if I want to add the National ID number field to 2 campaign ids only. Is the below approach correct?

```
if ((283 != $form->get_campaign()->ID) && (809 != $form->get_campaign()->ID)){
return $fields;
}
```

**Comment by ericnicolaas** [comment]
Yep, that would work. Or if you end up with a larger number of campaigns, you can use an array and `in_array` instead.

```
$campaigns = array( 283, 809 );

if ( ! in_array( $form->get_campaign()->ID, $campaigns ) ) {
     return $fields;
}
```
